spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/dauo
    username: sa
    password:
    driver-class-name: org.h2.Driver
    initialization-mode: always
  h2.console.enabled: true  # 웹 콘솔 사용 설정

  batch:
    jdbc:
      initialize-schema: always
jwt:
  secret-key: c88d74ba-1554-48a4-b549-b926f5d77c9e
  header: Authorization
  secret: fieldproject
  token-validity-in-seconds: 3600000


mybatis:
  type-aliases-pakage: tech.exam.dauo
  mapper-locations: mapper/*.xml

logging.level:
  level:
    jdbc.sqlonly: DEBUG ## 이부분 추가.
    org.springframework.web: DEBUG
    com.zaxxer.hikari.HikariDataSource: ERROR

client:
  ip: 127.0.0.1, 127.0.0.3
  savefilepath: C:\DATA_SAVE






