
DROP TABLE IF EXISTS DAUO_EXAM;

CREATE TABLE DAUO_EXAM
(
    REG_DTM      VARCHAR(14) PRIMARY KEY,
    JOIN_CNT     INT             NOT NULL,
    RESIGN_CNT   INT             NOT NULL,
    PAY_AMT      DECIMAL(18,0)  NOT NULL,
    USED_AMT     DECIMAL(18,0)  NOT NULL,
    SALES_AMT    DECIMAL(18,0)  NOT NULL
);